name: venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=2.116
  - blas-devel=3.9.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cpuonly=1.0
  - cudatoolkit=11.3.1
  - freetype=2.12.1
  - intel-openmp=2023.0.0
  - jpeg=9b
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libtiff=4.0.9
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.12
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - ninja=1.11.0
  - numpy=1.21.6
  - openssl=1.1.1t
  - pillow=9.3.0
  - pip=22.3.1
  - python=3.7.16
  - python_abi=3.7
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tbb=2021.5.0
  - tk=8.6.12
  - typing_extensions=4.5.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - wincertstore=0.2
  - zlib=1.2.12
  - pip:
    - charset-normalizer==3.1.0
    - cycler==0.11.0
    - fonttools==4.38.0
    - h5py==3.8.0
    - idna==3.4
    - keyboard==0.13.5
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pyparsing==3.0.9
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - python-dateutil==2.8.2
    - requests==2.28.2
    - six==1.16.0
    - torch==1.11.0+cu113
    - torchaudio==0.11.0+cu113
    - torchsummary==1.5.1
    - torchvision==0.12.0+cu113
    - urllib3==1.26.15
